### ISSUE TITLE
Just a small readme error

### ISSUE THREAD

**Issue by feider** [facebookresearch/TransCoder#1]
Hi,

just a small thing. In the readme it says: 

> If you run the data preprocessing pipeline, you will have to compile fastBPE. Go in preprocessing/tools/fastBPE and run: g++ -std=c++11 -pthread -O3 fastBPE/main.cc -IfastBPE -o fast

The correct path would have to be `XLM/tools/fastBPE`, and you would have to carry out the steps described in `XLM/tools/README.md` first.

Thank you very much for uploading the code!

**Comment by VinayChaudhari1996** [comment]
Can anyone just add
How to use it using Jupyter notebook ?

Need simple usecase for , 
1. Py to c++ 
2. Py to java

**Comment by brozi** [comment]
> Hi,
> 
> just a small thing. In the readme it says:
> 
> > If you run the data preprocessing pipeline, you will have to compile fastBPE. Go in preprocessing/tools/fastBPE and run: g++ -std=c++11 -pthread -O3 fastBPE/main.cc -IfastBPE -o fast
> 
> The correct path would have to be `XLM/tools/fastBPE`, and you would have to carry out the steps described in `XLM/tools/README.md` first.
> 
> Thank you very much for uploading the code!

Thanks feider. I corrected the README.

**Comment by brozi** [comment]
> Can anyone just add
> How to use it using Jupyter notebook ?
> 
> Need simple usecase for ,
> 
> 1. Py to c++
> 2. Py to java

If you want to translate using a jupyter notebook, you can use the Translator class in `translate.py`. Just initialize it with a `model_path` and a `BPE_path` and you will be able to translate using the `translate` method.
