### ISSUE TITLE
How to download github repos from BigQuery?

### ISSUE THREAD

**Issue by wasiahmad** [facebookresearch/TransCoder#13]
Can you provide some details on how to download the data in JSON format? It seems we can download a fraction of the data free of cost. However, the documentation is not easy to understand how to download the data in the JSON format. So, providing some details would be very helpful.

**Comment by malachaux** [comment]
Hi here is a little guide : 
- Create a Google platform account ( you will have around 300 $ given for free , that is sufficient for Github)
- Create a Google Big Query project [here](https://console.cloud.google.com/projectselector2/bigquery?supportedpurview=project)
- In this project, create a dataset
- In this dataset, create one table per programming language. The results of each SQL request (one per language) will be stored in these tables.
- Before running your SQL request, make sure you change the query settings to save the query results in the dedicated table (more -> Query Settings -> Destination -> table for query results -> put table name)
- Run your SQL request (one per language and dont forget to change the table for each request)
- Export your results to google Cloud :
     - In google cloud storage, create a bucket and a folder per language into it
     - Export your table to this bucket ( EXPORT -> Export to GCS -> export format JSON , compression GZIP)
- To download the bucket on your machine, use the API gsutil:
    - pip install gsutil
    - gsutil config  -> to config gsutil with your google account
    - gsutil -m cp -r gs://name_of_bucket/name_of_folder  .   -> copy your bucket on your machine


Example of query for python : 
```
SELECT 
 f.repo_name,
 f.ref,
 f.path,
 c.copies,
 c.content
FROM `bigquery-public-data.github_repos.files` as f
  JOIN `bigquery-public-data.github_repos.contents` as c on f.id = c.id
WHERE 
  NOT c.binary
  AND f.path like '%.py'
```

Google link for more info [here](https://console.cloud.google.com/getting-started?_ga=2.89118172.633087988.1597920386-1837687922.1590614229)

**Comment by wasiahmad** [comment]
**[To confirm]** Is an example query for Java and C++ looks as follows?

```
SELECT 
 f.repo_name,
 f.ref,
 f.path,
 c.copies,
 c.content
FROM `bigquery-public-data.github_repos.files` as f
  JOIN `bigquery-public-data.github_repos.contents` as c on f.id = c.id
WHERE 
  NOT c.binary
  AND f.path like '%.java'
```

And

```
SELECT 
 f.repo_name,
 f.ref,
 f.path,
 c.copies,
 c.content
FROM `bigquery-public-data.github_repos.files` as f
  JOIN `bigquery-public-data.github_repos.contents` as c on f.id = c.id
WHERE 
  NOT c.binary
  AND f.path like '%.cpp'
```

Also, I stored the python results to Google cloud, I see 187 files, each with a size of ~240MB. So, the total data size is around 45GB. Is it okay? I saw in the TransCoder paper that Python dataset size (All) is 224GB. Why do I see much smaller dataset size?

**Comment by malachaux** [comment]
Yes for your example queries for java / cpp !

The size you see are the size of compressed files (.json.gz). The size we give are uncompressed + tokenized !

**Comment by malachaux** [comment]
Feel free to close the issue when you're all set !
