### ISSUE TITLE
How to run preprocess　

### ISSUE THREAD

**Issue by taktak1** [facebookresearch/TransCoder#14]
I ran the command as instructed, but it doesn't work.

`python -m preprocessing.preprocess  ./data/test_dataset --lang1 java --lang2 python --lang3 cpp   --keep_comments True --bpe_train_size 0 --test_size 10 --local True
`

> cpp: process ...
> cpp: tokenizing 2 json files ...
> java: process ...
> java: tokenizing 2 json files ...
> 100% 50/50 [00:01<00:00, 29.15it/s]
> 100% 50/50 [00:01<00:00, 40.85it/s]
> java: split train, test and valid ... 
> python: process ...
> python: tokenizing 2 json files ...
> 100% 50/50 [00:03<00:00, 13.14it/s]
> 100% 50/50 [00:04<00:00, 12.36it/s]
> python: split train, test and valid ... 
> 100% 100/100 [00:18<00:00,  5.47it/s]
> 100% 150/150 [00:10<00:00, 14.43it/s]
> cpp: split train, test and valid ... 
> concurrent.futures.process._RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
>     r = call_item.fn(*call_item.args, **call_item.kwargs)
>   File "TransCoder/preprocessing/src/dataset.py", line 87, in process
>     nlines, size_gb = job.result()
>   File "TransCoder/preprocessing/src/utils.py", line 263, in result
>     self._result = self.func(*self.args, **self.kwargs)
>   File "TransCoder/preprocessing/src/dataset.py", line 51, in split_train_test_valid
>     size_gb = all_tok.stat().st_size
>   File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
>     return self._accessor.stat(self)
>   File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
>     return strfunc(str(pathobj), *args)
> FileNotFoundError: [Errno 2] No such file or directory: 'data/test_dataset/cpp/all.with_comments.tok'
> """

what is all.with_comments.tok?
Where is all.with_comments.tok located?

**Comment by taktak1** [comment]
Even after I made all.with_comments.tok
This problem also arises.

> File "TransCoder/preprocessing/src/utils.py", line 178, in learn_bpe_file
> assert process.returncode == 0, f"failed to learn bpe on {str(file_path)}"
> AssertionError: failed to learn bpe on data/test_dataset/cpp-java-python.with_comments/train.with_comments.tok.NoneGB

The error message will change when the first and second times are executed.

> File "TransCoder/preprocessing/src/utils.py", line 170, in apply_bpe_file
> output).is_file and process.returncode == 0, f"failed to apply bpe on {file_path}, command: \n {FAST} applybpe {output} {file_path} {codes} {vocab}"
> AssertionError: failed to apply bpe on data/test_dataset/cpp/train.with_comments.3.tok, command:
> TransCoder/XLM/tools/fastBPE/fast applybpe data/test_dataset/cpp-java-python.with_comments/cpp.train.with_comments.3.bpe data/test_dataset/cpp/train.with_comments.3.tok data/test_dataset/cpp-java-python.with_comments/codes

**Comment by orazheng** [comment]
Hi @taktak1 , did you solve this problem? I got the same error.

**Comment by malachaux** [comment]
Have you installed FastBPE , as mentioned [here](https://github.com/facebookresearch/TransCoder/#dependencies) ?

**Comment by orazheng** [comment]
> Have you installed FastBPE , as mentioned [here](https://github.com/facebookresearch/TransCoder/#dependencies) ?

@malachaux Yes, I have FastBPE installed.

**Comment by kchaksuvej** [comment]
> > Have you installed FastBPE , as mentioned [here](https://github.com/facebookresearch/TransCoder/#dependencies) ?
> 
> @malachaux Yes, I have FastBPE installed. when I use the remote machine, it shows `FileNotFoundError: [Errno 2] No such file or directory: 'data/test_dataset/cpp/all.with_comments.tok'`

Did you install fastBPE under XLM/tools/ folder?

**Comment by orazheng** [comment]
> > > Have you installed FastBPE , as mentioned [here](https://github.com/facebookresearch/TransCoder/#dependencies) ?
> > 
> > 
> > @malachaux Yes, I have FastBPE installed. when I use the remote machine, it shows `FileNotFoundError: [Errno 2] No such file or directory: 'data/test_dataset/cpp/all.with_comments.tok'`
> 
> Did you install fastBPE under XLM/tools/ folder?

@kchaksuvej Yes, I installed it under XLM/tools/.

**Comment by kchaksuvej** [comment]
This is what I run and it worked.
python -m preprocessing.preprocess /home/kit/transcoder/data/test_dataset --lang1 java --lang2 python --lang3 cpp --keep_comments True --bpe_train_size 0  --test_size 10 --local True

What is yours ? and what is the error ?

**Comment by orazheng** [comment]
> This is what I run and it worked.
> python -m preprocessing.preprocess /home/kit/transcoder/data/test_dataset --lang1 java --lang2 python --lang3 cpp --keep_comments True --bpe_train_size 0 --test_size 10 --local True
> 
> What is yours ? and what is the error ?

@kchaksuvej 
I run with `! python -m preprocessing.preprocess '/content/drive/My Drive/TransCoder/TransCoder/data/test_dataset' --lang1 java --lang2 python --lang3 cpp --keep_comments True --bpe_train_size 0 --test_size 10 --local True`

> cpp: process ...
java: process ...
cpp: tokenizing 2 json files ...
java: tokenizing 2 json files ...
100% 50/50 [00:01<00:00, 47.67it/s]
100% 50/50 [00:01<00:00, 29.20it/s]
java: split train, test and valid ... 
python: process ...
python: tokenizing 2 json files ...
100% 50/50 [00:03<00:00, 12.72it/s]
100% 50/50 [00:03<00:00, 12.71it/s]
python: split train, test and valid ... 
100% 150/150 [00:17<00:00,  8.42it/s]
100% 100/100 [00:14<00:00,  6.77it/s]
cpp: split train, test and valid ... 
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/content/drive/My Drive/TransCoder/TransCoder/preprocessing/src/dataset.py", line 87, in process
    nlines, size_gb = job.result()
  File "/content/drive/My Drive/TransCoder/TransCoder/preprocessing/src/utils.py", line 263, in result
    self._result = self.func(*self.args, **self.kwargs)
  File "/content/drive/My Drive/TransCoder/TransCoder/preprocessing/src/dataset.py", line 51, in split_train_test_valid
    size_gb = all_tok.stat().st_size
  File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
    return self._accessor.stat(self)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/TransCoder/TransCoder/data/test_dataset/cpp/all.with_comments.tok'
"""

> The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/drive/My Drive/TransCoder/TransCoder/preprocessing/preprocess.py", line 114, in <module>
    lang3=args.lang3, size_gb=args.bpe_train_size, test_size=args.test_size)
  File "/content/drive/My Drive/TransCoder/TransCoder/preprocessing/preprocess.py", line 65, in preprocess
    lang_executor=mp_executor, tok_executor=cluster_ex1, split_executor=cluster_ex2)
  File "/content/drive/My Drive/TransCoder/TransCoder/preprocessing/src/dataset.py", line 166, in process_languages
    self.sizes[lang.l] = jobs[i].result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/TransCoder/TransCoder/data/test_dataset/cpp/all.with_comments.tok'

**Comment by kchaksuvej** [comment]
Can you delete all .tok files in cpp, java, python folder ?
And run it again.

**Comment by orazheng** [comment]
@kchaksuvej still the same error...

**Comment by orazheng** [comment]
thank you for your help! I have solved the problem (the data path I put contains a space that's why it cannot pass the code).

**Comment by kchaksuvej** [comment]
Need help. 
Got error when run proprocess with new training data from BigQuery.  
Not sure what need to be fixed

    dataset.process_languages(
  File "/home/kit/transcoder/preprocessing/src/dataset.py", line 166, in process_languages
    self.sizes[lang.l] = jobs[i].result()
  File "/home/kit/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/kit/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
KeyError: 'content'

**Comment by pavelbatyr** [comment]
@kchaksuvej 
Some files from BigQuery come with 'content' field missing. 
So you can add this to function **process_and_tokenize_json_file** in preprocessing/src/utils.py:
   ```
if 'content' not in x:
            continue
```
right before
        `content = x['content']`

**Comment by kchaksuvej** [comment]
I fixed that error by add c.content IS NOT NULL in bigquery

But when I run pipeline, I got error and all .tok files has no data at all.

File "/home/kit/transcoder/preprocessing/src/utils.py", line 178, in learn_bpe_file
assert process.returncode == 0, f"failed to learn bpe on {str(file_path)}"

Any ideas ?

What bigquery that you used ?
I also Limit query only 50000


Thanks


regroup and select data for training bpe in /home/kit/transcoder/data/test_dataset/cpp-java-python.with_comments/train.with_comments.tok.NoneGB ...
adding 0 lines of /home/kit/transcoder/data/test_dataset/cpp/train.with_comments.2.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/cpp/train.with_comments.6.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/cpp/train.with_comments.5.tok
.
.
.
training bpe on /home/kit/transcoder/data/test_dataset/cpp-java-python.with_comments/train.with_comments.tok.NoneGB...
Traceback (most recent call last):
File "/home/kit/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/kit/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/kit/transcoder/preprocessing/preprocess.py", line 113, in
preprocess(args.root, args.lang1, args.lang2, args.keep_comments, args.local,
File "/home/kit/transcoder/preprocessing/preprocess.py", line 66, in preprocess
dataset.train_bpe(ncodes=ncodes, size_gb=size_gb)
File "/home/kit/transcoder/preprocessing/src/dataset.py", line 195, in train_bpe
learn_bpe_file(data_train_bpe, ncodes, self.codes)
File "/home/kit/transcoder/preprocessing/src/utils.py", line 178, in learn_bpe_file
assert process.returncode == 0, f"failed to learn bpe on {str(file_path)}"
AssertionError: failed to learn bpe on /home/kit/transcoder/data/test_dataset/cpp-java-python.with_comments/train.with_comments.tok.NoneGB

**Comment by pavelbatyr** [comment]
@kchaksuvej 
Is that cpp only problem?
I've noticed that cpp jsons from BigQuery are structured somewhat differently from java and python jsons and you might need to rewrite your parsing code accordingly if that's the case.

**Comment by kchaksuvej** [comment]
Same as python and java.
If I used sample data that come with /test_dataset. It works but not working on data that I extract from BigQuery.

Do you have any issue running preprocss with data from bigquery ?
What is your bigquery statement look like?

Thanks

adding 0 lines of /home/kit/transcoder/data/test_dataset/java/train.with_comments.3.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/java/train.with_comments.7.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/java/train.with_comments.0.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/python/train.with_comments.2.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/python/train.with_comments.6.tok

**Comment by pavelbatyr** [comment]
Preprocessing is not fully working for me either, I'm just working on errors that happen later in the pipeline.

My BigQuery query is identical to the one in README.md. I've only changed .py to .java and .cpp when I needed to get those.
And I run preprocessing like this:
`python3 -m preprocessing.preprocess /place/TransCoder/data/bigQueryLangs/ --lang1 java --lang2 python --keep_comments True --bpe_train_size 0 --test_size 10 --local True`

My generated .tok files are not of zero size.  Maybe it's worth checking that your files from BigQuery have .json.gz extension

**Comment by orazheng** [comment]
@kchaksuvej  How do you name the .json.gz files? Did you follow like `cpp.000.json.gz`? 
the code 
```
    def split_train_test_valid(self, keep_comments, test_size=1000):
        suffix = '.with_comments' if keep_comments else ''
        # split train-test-valid
        # regroup
        all_tok = self.folder.joinpath(f'all{suffix}.tok')
        command = f"cd '{self.folder}'; cat *[0-4][0-9][0-9]{suffix}.tok > {all_tok}"
```

needs you follow lang.[0-4][0-9][0-9] this format.

**Comment by kchaksuvej** [comment]
I use cpp.json.gz, python.json.gz

Do I have to use cpp.000.json.gz format instead? 

Thanks

**Comment by orazheng** [comment]
> I use cpp.json.gz, python.json.gz
> 
> Do I have to use cpp.000.json.gz format instead?
> 
> Thanks

yes, I think so. you can give it a try. I think this will explain why you get zero size for .tok files.

**Comment by keai007** [comment]
@kchaksuvej @orazheng 
Hi, do you know how to get parallel data to train AE & BT, like test.python_sa-cpp_sa.pth / valid.python_sa-cpp_sa.pth?

**Comment by orazheng** [comment]
@keai007 Do you have any idea about how to get parallel data?

**Comment by malachaux** [comment]
This repo is now deprecated. Please now refer to our new repository https://github.com/facebookresearch/CodeGen, which solves this issue.

**Comment by sushantkumar007007** [comment]
> thank you for your help! I have solved the problem (the data path I put contains a space that's why it cannot pass the code).

I am also getting the same error, How you resolved this ? Can you please explain

**Comment by sushantkumar007007** [comment]
> I ran the command as instructed, but it doesn't work.
> 
> `python -m preprocessing.preprocess ./data/test_dataset --lang1 java --lang2 python --lang3 cpp --keep_comments True --bpe_train_size 0 --test_size 10 --local True `
> 
> > cpp: process ...
> > cpp: tokenizing 2 json files ...
> > java: process ...
> > java: tokenizing 2 json files ...
> > 100% 50/50 [00:01<00:00, 29.15it/s]
> > 100% 50/50 [00:01<00:00, 40.85it/s]
> > java: split train, test and valid ...
> > python: process ...
> > python: tokenizing 2 json files ...
> > 100% 50/50 [00:03<00:00, 13.14it/s]
> > 100% 50/50 [00:04<00:00, 12.36it/s]
> > python: split train, test and valid ...
> > 100% 100/100 [00:18<00:00,  5.47it/s]
> > 100% 150/150 [00:10<00:00, 14.43it/s]
> > cpp: split train, test and valid ...
> > concurrent.futures.process._RemoteTraceback:
> > """
> > Traceback (most recent call last):
> > File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
> > r = call_item.fn(*call_item.args, **call_item.kwargs)
> > File "TransCoder/preprocessing/src/dataset.py", line 87, in process
> > nlines, size_gb = job.result()
> > File "TransCoder/preprocessing/src/utils.py", line 263, in result
> > self._result = self.func(*self.args, **self.kwargs)
> > File "TransCoder/preprocessing/src/dataset.py", line 51, in split_train_test_valid
> > size_gb = all_tok.stat().st_size
> > File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
> > return self._accessor.stat(self)
> > File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
> > return strfunc(str(pathobj), *args)
> > FileNotFoundError: [Errno 2] No such file or directory: 'data/test_dataset/cpp/all.with_comments.tok'
> > """
> 
> what is all.with_comments.tok? Where is all.with_comments.tok located?

Hey I am getting the same error, how did to manage to run? please explain
