### ISSUE TITLE
pipeline run error

### ISSUE THREAD

**Issue by kchaksuvej** [facebookresearch/TransCoder#18]
I run pipeline using new data for python, java, cpp from using this bigquery

SELECT 
 f.repo_name,
 f.ref,
 f.path,
 c.content
FROM `bigquery-public-data.github_repos.files` as f
  JOIN `bigquery-public-data.github_repos.contents` as c on f.id = c.id
WHERE 
  NOT c.binary
  AND f.path like '%.py'                  #.cpp, .java
  AND c.content IS NOT NULL 
limit 50000

But when I run pipeline, I got error and all .tok files has no data at all.

  File "/home/kit/transcoder/preprocessing/src/utils.py", line 178, in learn_bpe_file
    assert process.returncode == 0, f"failed to learn bpe on {str(file_path)}"

If I used sample data that come whith Gihub and run pipeline, there is data in *.tok file.

What is wrong with my query ?
Do you have query that you used to create sample data in /transcoder/data/test_dataset?

Thanks

regroup and select data for training bpe in /home/kit/transcoder/data/test_dataset/cpp-java-python.with_comments/train.with_comments.tok.NoneGB ...
adding 0 lines of /home/kit/transcoder/data/test_dataset/cpp/train.with_comments.2.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/cpp/train.with_comments.6.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/cpp/train.with_comments.5.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/cpp/train.with_comments.4.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/cpp/train.with_comments.1.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/cpp/train.with_comments.3.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/cpp/train.with_comments.7.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/cpp/train.with_comments.0.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/java/train.with_comments.2.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/java/train.with_comments.6.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/java/train.with_comments.5.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/java/train.with_comments.4.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/java/train.with_comments.1.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/java/train.with_comments.3.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/java/train.with_comments.7.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/java/train.with_comments.0.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/python/train.with_comments.2.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/python/train.with_comments.6.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/python/train.with_comments.5.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/python/train.with_comments.4.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/python/train.with_comments.1.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/python/train.with_comments.3.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/python/train.with_comments.7.tok
adding 0 lines of /home/kit/transcoder/data/test_dataset/python/train.with_comments.0.tok
training bpe on /home/kit/transcoder/data/test_dataset/cpp-java-python.with_comments/train.with_comments.tok.NoneGB...
Traceback (most recent call last):
  File "/home/kit/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kit/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kit/transcoder/preprocessing/preprocess.py", line 113, in <module>
    preprocess(args.root, args.lang1, args.lang2, args.keep_comments, args.local,
  File "/home/kit/transcoder/preprocessing/preprocess.py", line 66, in preprocess
    dataset.train_bpe(ncodes=ncodes, size_gb=size_gb)
  File "/home/kit/transcoder/preprocessing/src/dataset.py", line 195, in train_bpe
    learn_bpe_file(data_train_bpe, ncodes, self.codes)
  File "/home/kit/transcoder/preprocessing/src/utils.py", line 178, in learn_bpe_file
    assert process.returncode == 0, f"failed to learn bpe on {str(file_path)}"
AssertionError: failed to learn bpe on /home/kit/transcoder/data/test_dataset/cpp-java-python.with_comments/train.with_comments.tok.NoneGB

**Comment by orazheng** [comment]
Hi @kchaksuvej, did you figure this problem out? I got the same error.

**Comment by kchaksuvej** [comment]
No

**Comment by malachaux** [comment]
This repo is now deprecated. Please now refer to our new repository https://github.com/facebookresearch/CodeGen, which solves this issue.
