### ISSUE TITLE
Request: add requirements.txt (or analog)

### ISSUE THREAD

**Issue by m1kc** [facebookresearch/TransCoder#23]
subj

**Comment by QuentinN42** [comment]
Working on PR.

**Comment by QuentinN42** [comment]
[Here](https://github.com/facebookresearch/TransCoder/pull/27).

**Comment by malachaux** [comment]
This repo is now deprecated. Please now refer to our new repository https://github.com/facebookresearch/CodeGen, which solves this issue, you have install_env.sh
