### ISSUE TITLE
how to run translate.py without GPU?

### ISSUE THREAD

**Issue by abhishekgoldypathak** [facebookresearch/TransCoder#33]
Is it possible to run using only CPU? I have tried to run it by changing all instances of 

device='cuda:0'

to device='cpu'

or setting CUDA_VISIBLE_DEVICES="" etc

but nevertheless not able to git rid of all the errors regardless of what I try. What's the easy way to run it on a CPU only machine?

**Comment by brozi** [comment]
Did you also change all the instances where the `.cuda()` is called on a tensor? For instance in the `to_cuda(*args)` method.
