### ISSUE TITLE
AssertionError: The path to the BPE tokens is incorrect

### ISSUE THREAD

**Issue by Skylixia** [facebookresearch/TransCoder#36]
Hi,

I'm running the following command:
` python translate.py --src_lang cpp --tgt_lang python --model_path model_2.pth < code_to_be_translated.cc`
But I get the error:
```
Traceback (most recent call last):
  File "TransCoder/translate.py", line 166, in <module>
    params.BPE_path), f"The path to the BPE tokens is incorrect: {params.BPE_path}"
AssertionError: The path to the BPE tokens is incorrect: data/BPE_with_comments_codes
```
I installed the dependencies, including fastBPE following the readme commands (in XLM/tools)
Should I provide a BPE_path in my command ? I didn't provide any as in the Read me example none is provided. If yes, what is the BPE_path that should be given (what to install, where to find, ...)

Thanks !

**Comment by msakthi19** [comment]
Hi @Skylixia,

Here are the steps I followed to solve the issue at my end.  Mentioning the entire process to make sure it's easier to understand.

```
cd transcoder/XML/tools/
git clone https://github.com/glample/fastBPE
cd fastBPE
g++ -std=c++11 -pthread -O3 fastBPE/main.cc -IfastBPE -o fast
pip install Cython (if you haven't installed already)
python setup.py install
```

1. Once you're done with the above steps, go to the `transcoder` folder and open `translate.py`.  

2. Ensure you have the correct path in lines (46,47) to the `BPE_with_comments_codes` file which can be found under `transcoder/data/BPE_with_comments_codes`. Ensure you provide the correct relative path in the default argument with respect to the folder from where you're running the script. Alternatively, you can also try passing it as an argument.

```
    parser.add_argument("--BPE_path", type=str,
                        default="transcoder/data/BPE_with_comments_codes", help="Path to BPE codes.")
```

I was able to fix the issue with these steps. Let me know if it works!

**Comment by malachaux** [comment]
This repo is now deprecated. Please now refer to our new repository https://github.com/facebookresearch/CodeGen, which solves this issue, and contains a more details readme on the pipeline.
