### ISSUE TITLE
What's <DOCUMENT_ID=\"{path}\"> for?

### ISSUE THREAD

**Issue by overwindows** [facebookresearch/TransCoder#37]
Why is the 'content_tokenized' surrounded by <DOCUMENT> 's = f"<DOCUMENT_ID=\"{path}\"> {content_tokenized} </DOCUMENT>"' ?

**Comment by moraitis55** [comment]
I am wondering the same thing now.

**Comment by malachaux** [comment]
Just the description of how our test/valid files are composed. In our case content_tokenized is the tokenized functions.
