### ISSUE TITLE
Which part of the code should I modify when I only have CPU available on my machine ?

### ISSUE THREAD

**Issue by yaoxingcheng** [facebookresearch/TransCoder#4]
I seems that the current code only supports a machine with CUDA driver. But if I only want to train a model with CPU, how should I modify the code to achieve that?

**Comment by brozi** [comment]
I don't expect you to be able to train a good model in a reasonable amount of time using only CPUs. 
If you know better and still want to do it, you will need to modify the code under `XLM/`. Although we never tried it, I guess you will be able to train on CPU if you remove all the calls to `to_cuda()` and `.cuda()`.
