### ISSUE TITLE
bpe.cpp-java-python.with_comments only has vocab file

### ISSUE THREAD

**Issue by peterzsj6** [facebookresearch/TransCoder#40]
According to read me, both vocab and code file is provided for cpp/java/python with comments. But I only found the vocab file.

**Comment by malachaux** [comment]
This repo is now deprecated. Please now refer to our new repository https://github.com/facebookresearch/CodeGen, which solves this issue.

**Comment by skye95git** [comment]
> This repo is now deprecated. Please now refer to our new repository https://github.com/facebookresearch/CodeGen, which solves this issue.

 Hi, you describe in the readme of TransCoder `If you run the pipeline for cpp/java/python with --keep-comments True, you simply have to add a folder cpp-java-python.with_comments and copy the codes and vocab files.` But there is no `--keep-comments` parameter in CodeGen. How to keep comments when I extract functions?
