### ISSUE TITLE
Multi-bleu.perl file not found 

### ISSUE THREAD

**Issue by carlguo866** [facebookresearch/TransCoder#41]
In evaluator.py, the code now tries to download a `multi-bleu.perl` from `BLEU_SCRIPT_URL = 'https://raw.githubusercontent.com/facebookresearch/XLM/master/src/evaluation/multi-bleu.perl'`. However, there isn't such a file in this repo. I found `multi-bleu.perl` from the Moses repo [here](https://raw.githubusercontent.com/moses-smt/mosesdecoder/master/scripts/generic/multi-bleu.perl). Is there any difference between the TransCoder one and the original Moses one?

**Comment by dowenk** [comment]
I'm having same issue.  What did you do to circumvent?

**Comment by carlguo866** [comment]
do`wget https://raw.githubusercontent.com/moses-smt/mosesdecoder/master/scripts/generic/multi-bleu.perl` and then you would be fine

**Comment by malachaux** [comment]
This repo is now deprecated. Please now refer to our new repository https://github.com/facebookresearch/CodeGen, which solves this issue.
