### ISSUE TITLE
test_dataset.py missing

### ISSUE THREAD

**Issue by alantwm** [facebookresearch/TransCoder#6]
In the readme it says the following:

"To test the pipeline run pytest preprocessing/test_dataset.py, you will see the pipeline output in data/test_dataset folder."

I'm unable to find the test_dataset.py file. Am I missing something?

**Comment by malachaux** [comment]
Thank you for flagging this small issue in readme, the correct script is  preprocessing/test_preprocess.py not  preprocessing/test_dataset.py
