### ISSUE TITLE
Multiple translation

### ISSUE THREAD

**Issue by mahimanzum** [facebookresearch/TransCoder#7]
Is there any way to modify the translate.py file to translate a batch of code files to a target language using this model?

**Comment by brozi** [comment]
Yes you can. The `Translator` object loads the model in the `__init__` and you can make your translations much more efficient by creating it only once and calling `translator.translate` on all your files afterwards. You can also make it much faster by sending batches of functions through the model. You only need to modify the line where x1 is created (l 124) and the other operations can be done by batch.
